version: '3.8'

volumes:
  postgres_data: { }

services:

  postgres:
    image: postgres:13.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: distribution
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup/0_init.sql:/docker-entrypoint-initdb.d/0_init.sql:ro
      - ./setup/1_seed.sql:/docker-entrypoint-initdb.d/1_seed.sql:ro