---
openapi: "3.1.0"
info:
  version: 1.0.0
  title: Current distribution API
  description: This API handles distribution of current between charge points in a charge point group

paths:
  "/get":
    get:
      description: Get all the current distribution between charge points in groups from database
      responses:
        '200':
          description: List of maps with charge point id and current
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/GetResponse"
        '500':
          description: Internal server error with message
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/Response"

  "/group/":
    post:
      description: Create a new group with maximal current
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/CreateGroup"
      responses:
        '200':
          description: Success message
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Response"
        '500':
          description: Internal server error with message
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/Response"

  "/charge-point":
    post:
      description: Add a new charge point with group id and priority
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/AddChargePoint"
      responses:
        '200':
          description: Success message
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Response"
        '500':
          description: Internal server error with message
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/Response"

  "/charge-point-connector":
    post:
      description: Add a new charge point connector with status for specific charge point
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/AddChargePointConnector"
      responses:
        '200':
          description: Success message
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Response"
        '500':
          description: Internal server error with message
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/Response"

    "/charge-point":
    put:
      description: Update a charge point with priority by id
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UpdateChargePoint"
      responses:
        '200':
          description: Success message
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Response"
        '500':
          description: Internal server error with message
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/Response"

    "/charge-point-connector":
    put:
      description: Update a charge point connector with status by id
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UpdateChargePointConnector"
      responses:
        '200':
          description: Success message
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Response"
        '500':
          description: Internal server error with message
          content:
            "application/json":
              schema:
                  $ref: "#/components/schemas/Response"

components:
  schemas:
    Response:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          example: "Success"
        message:
          type: string
          example: "Group with maximal current 20 created!"

    GetResponse:
      type: object
      required:
        - status
        - message
        - data
      properties:
        status:
          type: string
          example: "Success"
        message:
          type: string
          example: "Group with maximal current 20 created!"
        data:
          type: object
          required:
            - charge_point_id
            - current
          properties:
            charge_point_id:
              type: uint
              example: 1
            current:
              type: float32
              example: 10.25
    
    CreateGroup:
      type: object
      required:
        - groupId
      properties:
        groupId:
          type: uint
          example: 1
    
    AddChargePoint:
      type: object
      required:
        - groupId
        - priority
      properties:
        groupId:
          type: uint
          example: 1
        priority:
          type: int
          example: 2
    
    UpdateChargePoint:
      type: object
      required:
        - id
        - priority
      properties:
        id:
          type: uint
          example: 1
        priority:
          type: int
          example: 5

    AddChargePointConnector:
      type: object
      required:
        - chargePointId
        - status
      properties:
        chargePointId:
          type: uint
          example: 1
        status:
          type: string
          example: "Charging"

    UpdateChargePointConnector:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: uint
          example: 1
        status:
          type: string
          example: "Charging"
